// resources/js/Pages/Station/PrintStation/Modals/DeleteModal.tsx
import React from 'react';
import { Inertia } from '@inertiajs/inertia';

type Props = { open: boolean; id: number | null; onClose: () => void };

export default function DeleteModal({ open, id, onClose }: Props) {
  if (!open || !id) return null;

  function destroy() {
    Inertia.delete(route('station.print.destroy', id));
    onClose();
  }

  return (
    <div className="fixed inset-0 flex items-center justify-center z-50">
      <div className="bg-white p-6 rounded shadow">
        <h3 className="font-bold">Hapus file?</h3>
        <div className="mt-4 flex gap-2">
          <button onClick={destroy} className="btn btn-danger">Delete</button>
          <button onClick={onClose} className="btn">Cancel</button>
        </div>
      </div>
    </div>
  );
}

// resources/js/Pages/PrintStation/Modals/DeleteModal.vue
<script setup>
import { Trash2 } from 'lucide-vue-next';

defineProps({
    show: Boolean,
    title: {
        type: String,
        default: 'Hapus File?'
    },
    message: {
        type: String,
        default: 'File ini akan dihapus permanen dari server.'
    },
    confirmText: {
        type: String,
        default: 'Hapus'
    },
    isBulk: Boolean
});

defineEmits(['close', 'confirm']);
</script>

<template>
    <div v-if="show" class="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 backdrop-blur-sm">
        <div class="bg-white rounded-2xl p-8 w-96 text-center shadow-xl">
            <div v-if="isBulk"
                class="w-16 h-16 bg-red-50 text-red-600 rounded-full flex items-center justify-center mx-auto mb-4">
                <Trash2 class="w-8 h-8" />
            </div>
            <h3 class="text-xl font-bold text-gray-900 mb-2">{{ title }}</h3>
            <p class="text-gray-500 mb-6">{{ message }}</p>
            <div class="flex gap-3">
                <button @click="$emit('close')"
                    class="flex-1 py-3 bg-gray-100 hover:bg-gray-200 rounded-xl font-bold text-gray-700">
                    Batal
                </button>
                <button @click="$emit('confirm')"
                    class="flex-1 py-3 bg-red-600 hover:bg-red-700 rounded-xl font-bold text-white shadow-lg shadow-red-200">
                    {{ confirmText }}
                </button>
            </div>
        </div>
    </div>
</template>
